[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcutil"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/mutecomm/go-sqlcipher"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/tyler-smith/go-bip39"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/asticode/go-astilectron"

[[override]]
  branch = "master"
  name = "github.com/chzyer/readline"
